spring.application.name=jenkins-cicd-demo
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
info.app.name=Jenkins CI/CD Demo
info.app.version=1.0.0
